### ISSUE TITLE
Crash with quark

### ISSUE THREAD

**Issue by meelock** [Elix-x/Skyblocks#2]
For some reason, this mod crashes when put in conjunction with vazkii's mod Quark, at least by my tests.

Crash log: [Crash](http://paste.ubuntu.com/25049813/)

**Comment by meelock** [comment]
AkashicTome-1.1-7.jar                                     
AppleCore-mc1.11.2-2.2.0.jar                              
AppleSkin-mc1.11-1.0.7.jar                                
Architect-MC1.11.2-1.1.3.56.jar                           
astralsorcery-1.4.5.jar                                   
AutoRegLib-1.1-4.jar                                      
Batty's Coordinates PLUS Mod for Forge-1.11.2_003.jar     
BetterFoliage-MC1.11.2-2.1.6.jar.disabled                 
BiblioCraft[v2.3.2][MC1.11.2].jar.disabled                
Blur-1.0.3-13.jar                                         
BrandonsCore-1.11.2-2.2.1.115-universal.jar               
buildcraft-7.99.6.jar.disabled                            
Chameleon-1.11.2-3.1.0.jar                                
CodeChickenLib-1.11.2-3.0.0.284-universal.jar             
compatlayer-1.11.2-0.2.9.jar                              
computality-1.11.2-1.82.jar                               
Controlling-2.0.5.jar                                     
CraftTweaker-1.11.2-3.0.26.jar                            
Draconic-Evolution-1.11.2-2.2.1.248-universal.jar         
DynamicSurroundings-1.11.2-3.4.5.7.jar                    
embers-0.220.jar                                          
enderutilities-1.11.2-0.7.1.jar                           
funky-locomotion-1.11.2-alpha-0.0.1.jar                   
Hwyla-1.8.15-B29_1.11.jar                                 
ic2                                                       
ImmersiveEngineering-0.11-63.jar                          
immersivepetroleum-1.11.2-1.0.7.jar                       
industrialcraft-2-2.7.74-ex111.jar                        
industrialforegoing-1.11.2-0.3-16.jar                     
IndustrialWires-1.5-13.jar                                
ironchest-1.11.2-7.0.25.815.jar                           
IvToolkit-1.3.3.jar                                       
JAOPCA-1.11.2-1.1.18.jar                                  
jei_1.11.2-4.5.0.291.jar                                  
jepb-1.11.2-1.2.jar                                       
journeymap-1.11.2-5.4.7.jar                               
JustAFewFish-1.6_for_1.11.2.jar                           
JustEnoughResources-1.11.2-0.6.6.12.jar                   
keywizard-1.11.2-1.4.5.jar                                
LingeringLoot-1.11.2-3.0.jar.disabled                     
lostcities-1.1x-0.0.16beta.jar                            
modtweaker-3.0.1.jar                                      
Morph-o-Tool-1.1-13.jar                                   
MTLib-2.0.3.jar                                           
multistorage-1.11.0-1.3.7b.jar                            
netherchest-0.1.1.jar                                     
NotEnoughPotions-1.4_for_1.11.2.jar.disabled              
Notes-1.11.2-1.1.1.jar                                    
PotionCore-1.5.2_for_1.11.2.jar                           
ProjectTable-1.0.3_1.11.2.jar                             
Quark-r1.2-93.jar                                         
RandomThings-MC1.11.2-4.0.jar                             
RecurrentComplex-1.4.4-1.11.jar                           
RefinedRelocation-mc1.11.2-3.1.14.jar                     
refinedstorage-1.4.18.jar                                 
roots-2-0.025.jar                                         
rustic-0.3.7.jar                                          
shetiphiancore-1.11.0-3.4.6.jar                           
Skyblocks-0.0.4-alpha-1.11.2.jar             
SoulShards-TOW-1.11-2.6.6-47.jar                          
SpiceOfLife-mc1.11.2-1.3.9.jar                            
StorageDrawers-1.11.2-4.2.10.jar                          
Tesla-1.11-1.3.0.52.jar                                   
tesla-core-lib-1.11.2-0.7.3.jar                           
Trapcraft-1.11.2-v2.4.2.a-universal.jar                   
usefulnullifiers-1.3.5.jar                                
WailaHarvestability-mc1.11-1.1.10.jar

**Comment by Elix-x** [comment]
This crash is similar to #1. In fact, it crashes for the same reason. Which is already fixed in 1.12.
Though i have 2 news for you.
The bad one is that i no longer support 1.11, so i won't be able to fix it.
The good one is that you can fix this crash yourself by changing config:
1. Open skyblocks config
2. Go to the recipe section - it is empty by default (aka no recipe).
3. Change the recipe, either to Open Blocks' recipe (given in comment above) or anything else.

**Comment by Elix-x** [comment]
Fixed since release on 1.12.
Does not exist in beta.
