### ISSUE TITLE
Client render crash 1.12.1

### ISSUE THREAD

**Issue by DingoX3** [Elix-x/Skyblocks#3]
Created a sp world. Was able to walk around for approx a minute then it crashed. Wasnt really doing anything but walking forward and loading a possible chunk that included one of your skyblocks.

full crash: https://pastebin.com/7tAgyFzj
MC: 1.12.1
ModPack: Stella (twitch launcher)
Forge: 2474
skyblock: 0.1.1-alpha-1.12.1

**Comment by Elix-x** [comment]
Ok. I haven't had any reports of this, and i know it worked for others.

Please try adding the latest EXCore and see what happens.

**Comment by DingoX3** [comment]
Crashed when loading with latest version of EXCore. Also i noticed EXCore doesnt install when adding skyblocks on the twitch launcher. Is this intended? Its also not listed on there yet.

full crash: https://pastebin.com/PtSf0iNE

**Comment by Elix-x** [comment]
Did you get the EXCore on curseforge? Does the EXCore file have `-obf` suffix on the end?
Because the new crash actually looks like CI issue.

As for Skyblocks & EXCore - yes it is intended. Skyblocks is very lightweight, and it ships (_should at least_) necessary parts of EXCore.

**Comment by DingoX3** [comment]
I got it from your github releases. (EXCore-2.0.0-alpha15-1.12.1.jar) Its not in the twitch launcher that i saw. Ok thanks for the explanation on the download.

**Comment by Elix-x** [comment]
That makes sense then :D (_there's a tiny subtle difference between files on github releases and on CF_).

EXCore is in alpha, so it does not show up on curse &client. Get the actual file you need [here](https://minecraft.curseforge.com/projects/excore/files/2464558).

**Comment by DingoX3** [comment]
Everthing looks good so far. I even spawned some blocks in and placed them around to make sure. Sorry about turning this into a big event just to get one core file. I took you literally when you said get the latest version...lol I hunted it down and got it. Thanks for your help with this. Ill report it to the modpack author in case anyone else has the same issue.

**Comment by DingoX3** [comment]
Adding latest EXCore fixed the issue.

**Comment by Elix-x** [comment]
So the fix on your side is clear, and i know how to fix it on my side for future builds.

I'll resume it in #4, to not ping you :) .
